shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2010
  - TOOLSET: vs2012
  - TOOLSET: vs2013
  - TOOLSET: vs2015

configuration:
  - debug
  - release
  
install:
  - tools\bin\windows\genie %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/enkone.sln
