compiler:
  - clang
  - gcc

language: c

script:
    - if [ "$CC" == "clang" ]; then make linux-clang; fi
    - if [ "$CC" == "gcc" ]; then make linux-gcc; fi
    - $CC --version
notifications:
    email: false