compiler:
  - clang
  - gcc

language: c

before_install: 
  - chmod a+x tools/genie/linux/genie

script:
  - if [ "$CC" == "clang" ]; then make linux-clang; fi
  - if [ "$CC" == "gcc" ]; then make linux-gcc; fi
  - $CC --version
notifications:
  email: false