compiler:
  - clang
  - gcc

language: c

script:
    - if [ "$CXX" == "clang++" ]; then make linux-clang; fi
    - if [ "$CXX" == "g++" ]; then make linux-gcc; fi
    
notifications:
    email: false